version: '2'
services:
    legtech-app:
        image: legtech
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://legtech-mysql:3306/legtech?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    legtech-mysql:
        extends:
            file: mysql.yml
            service: legtech-mysql
